# Set working language
language: c

# It's needed to install g++4.8 correctly
dist: trusty

# Additional packages
addons:
    apt:
        packages:
        - libgtest-dev
        - g++-4.8

# Finish GTest installation
before_script: cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && cd -

# Build and test script
script: mkdir -p _build && cd _build && cmake .. && make && test/test

